/* FILTRANDO VALORES NULOS */
SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE EMAIL IS NULL;

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE EMAIL IS NOT NULL;

/* IS OU IS NOT NULL */ 

/* UTILIZANDO O UPDATE PARA ATUALIZAR OS VALORES */

SELECT NOME, EMAIL FROM CLIENTE;

UPDATE CLIENTE SET EMAL = 'JORGER@GMAIL.COM';


/* WHERE - VAI SER O SEU MELHOR AMIGO DA VIDA PARA A VIDA INTEIRA */

SELECT NOME, EMAIL FROM CLIENTE
WHERE NOME = 'JORGE';

/* EMAIL = NULL */

UPDATE CLIENTE
SET EMAIL = 'JORGE@GAMIL.COM'
WHERE NOME = 'JORGE';

UPDATE CLIENTE
SET EMAIL = 'JULIA@GAMIL.COM'
WHERE NOME = 'JULIA'