/* DELETANDO REGISTRO COM A CLUSULA DELETE */

-- DELETE FROM CLIENTE;

SELECT * FROM CLIENTE WHERE NOME = 'ANA';

SELECT COUNT(*) FROM CLIENTE; -- TOTAL 6

DELETE FROM CLIENTE -- TOTAL 1
WHERE NOME = 'ANA';

SELECT COUNT(*) FROM CLIENTE; -- TOTAL 5

SELECT 6 - 1;

SELECT * FROM CLIENTE;

INSERT INTO CLIENTE VALUES('CARLA','F','CLAUDIA@GMAIL.COM',1236547, '75648-0048','RUA COPPER LEAF - WILIANSBURG - CANADA');


/* CASO NÃO TENHA CONFIANÇA OU TENHA DUVIDA OPTE PELO SELECT AO INVES DE DELETE */
SELECT * FROM CLIENTE WHERE NOME = 'CARLA'
OR EMAIL = 'LILIAN@GMAIL.COM';

DELETE FROM CLIENTE WHERE NOME = 'CARLA' -- OR TRAS TODO MUNDO COM APENAS UMA DAS DUAS CONDIÇOES
OR EMAIL = 'LILIAN@GMAIL.COM';

DELETE FROM CLIENTE WHERE NOME = 'CARLA' -- AND TRAZ APENAS O REGISTRO QUE SATISFAÇA AS DUAS CONDIÇOES
AND EMAIL = 'LILIAN@GMAIL.COM';