/* O COMANDO SELECT 

seleção projeção e junção
*/

SELECT NOW() as DATA_HORA, 'GUILHERME ARAUJO' as ALUNO;

SELECT 'GUILHERME ARAUJO';

SELECT 'BANCO DE DADOS';

/* ALIAS DE COLUNAS */

SELECT NOME as CLIENTE, SEXO, EMAIL FROM CLIENTE;

SELECT NOME, SEXO, EMAIL, ENDERECO FROM CLIENTE; 

SELECT EMAIL, SEXO, ENDERECO, NOME FROM CLIENTE; 

SELECT EMAIL, SEXO, ENDERECO, NOME, NOW() as DATA_HORA FROM CLIENTE; 


/* APENAS PARA FINS ACADEMICOS */

SELECT * FROM CLIENTE;

/* TABELA ERRADA - NÃO DIGITE DIRETAMENTE NO BANCO */
CREATE TABLE CLIENTE_ERRO(
	NOME VARCHAR(30),
	SEXO CHAR(1),
	EMAIL VARCHAR(30)
	CPF INT(11),
	TELEFONE VARCHAR(30),
	ENDERECO VARCHAR(100),

);