-- SELEÇÃO, PROJEÇÃO E JUNÇÃO 

-- PROJEÇÃO -> É TUDO QUE VOCÊ QUER VER NA TELA

    SELECT NOW() AS DATA_ATUAL;

    SELECT 2 + 2 AS SOMA;

    SELECT 2 + 2 AS SOMA, NOME, NOW() FROM CLIENTE;

-- SELEÇÃO -> É UM SUBCONJUNTO DO CONJUTO TOTAL DE REGISTROS DE UMA TABELA A CLAUSULA DE SELEÇÃO É O WHERE

    SELECT NOME, SEXO, EMAIL FROM CLIENTE
    WHERE SEXO = 'F';

    SELECT NUMERO FROM TELEFONE
    WHERE TIPO = 'CEL';

-- JUNÇÃO -> JOIN

    SELECT NOME, EMAIL, IDCLIENTE FROM CLIENTE;

    SELECT ID_CLIENTE, BAIRRO, CIDADE FROM ENDERECO;

        -- PROJETAR NOME, SEXO, BAIRRO, CIDADE

        SELECT NOME, SEXO, BAIRRO, CIDADE FROM CLIENTE, ENDERECO
        WHERE IDCLIENTE = ID_CLIENTE;


        -- NÃO UTILIZAR O WHERE PARA JUNÇÃO APENAS PARA **SELEÇÃO**


-- UTILIZANDO A SELEÇÃO, PROJEÇÃO E JUNÇÃO 

SELECT NOME, SEXO, BAIRRO, CIDADE /* PROJEÇÃO */ 
FROM CLIENTE /* ORIGEM */  
    INNER JOIN ENDERECO /* JUNÇÃO */
    ON IDCLIENTE = ID_CLIENTE
WHERE SEXO = 'F'; /* SELEÇÃO */


SELECT NOME, SEXO, EMAIL, TIPO, NUMERO
FROM CLIENTE
    INNER JOIN TELEFONE
    ON IDCLIENTE = ID_CLIENTE;


/* NOME, SEXO, CIDADE, BAIRRO, TIPO, NUMERO */

-- PODEMOS IDENTAR AS TABELAS DE DUAS FORMAS. 
SELECT CLIENTE.NOME, CLIENTE.SEXO, ENDERECO.CIDADE, ENDERECO.BAIRRO, TELEFONE.TIPO, TELEFONE.NUMERO
FROM CLIENTE 
    INNER JOIN ENDERECO
    ON CLIENTE.IDCLIENTE = ENDERECO.ID_CLIENTE
    INNER JOIN TELEFONE
    ON CLIENTE.IDCLIENTE = TELEFONE.ID_CLIENTE;

SELECT C.NOME, C.SEXO, E.CIDADE, E.BAIRRO, T.TIPO, T.NUMERO
FROM CLIENTE C
    INNER JOIN ENDERECO E
    ON C.IDCLIENTE = E.ID_CLIENTE
    INNER JOIN TELEFONE T
    ON C.IDCLIENTE = T.ID_CLIENTE;


/*

    DML - DATA MANIPULATION LAGUAGE
    DDL - DATA DEFINICIO LAGUAGE
    DCL - DATA CONTROL LAGUAGE
    TCL - TRANSARION CONTROL LANGUAGE 

*/

-- INSERT

INSERT INTO CLIENTE VALUES(NULL,'PAULA','M',NULL,'789654789');
INSERT INTO ENDERECO VALUES(NULL,'RUA JOAQUIM SILVA', 'ALVORADA','NITEROI','RJ', 18);

SELECT * FROM CLIENTE;

-- FILTROS

SELECT * FROM CLIENTE
WHERE SEXO = 'M';

-- UPDATE
UPDATE CLIENTE
SET SEXO = 'F'
WHERE IDCLIENTE = 18 ;

/* DELETE */

INSERT INTO CLIENTE VALUES(NULL,'PAULA', 'M'. NULL, '789654789');

DELETE FROM CLIENTE
WHERE IDCLIENTE = 20;