/*  MODELAGEM A PRIMEIRA FORMA NORMAL */


INSERT INTO CLIENTE VALUES('CARLA','F','C.LOPES@UOL.COM', 1236547,'9301-7585','RUA COPPER LEAF - WILIANSBURG - CANADA');

SELECT SEXO, COUNT(*) AS QTD FROM CLIENTE
GROUP BY SEXO;

/* PRIMEIRA FORMA NORMAL */


/*

1 - TODO CAMPO VETORIZADO SE TORNARÁ OUTRA TABELA

[AMARELO, AZUL, LARANJA, VERDE] -> CORES
[KA, FIESTA, UNO, CIVIC] -> CARROS


2 - TODO CAMPO MULTIVALORA SE TORNARÁ OUTRA TABELA, OU QUANDO O CAMPO FOR DIVISÍVEL


3 - TODA TABELA NESSECITA DE PELO MENOS UM CAMPO QUE IDENTIFIQUE TODO O REGISTRO COMO SENDO UNICO, ISSO É O O QUE CHAMAMOS DE CHAVES PRIMARIA OU PRIMARY KEY.

*/

-- QUEM DEFINE A CARDINALIDADE É A REFRA DE NEGOCIOS 

/* 
O PROMIRO ALGARISOMO - OBRIGATORIAMENTE 

0 - NÃO OBRIGATORIO
1 - OBRIGATORIO

SEGUNDO ALGARISMO - CARDIANALIDADE
1 - MAXIMO DE UM
N - MAIS DE UM

*/


CREATE DATABASE COMERCIO;
USE COMERCIO;

-- TABELA CLIENTE
CREATE TABLE CLIENTE(
    IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL,
    SEXO ENUM('M','F') NOT NULL,
    EMAIL VARCHAR(50) UNIQUE,
    CPF VARCHAR(15) UNIQUE

);


-- TABELA ENDERECO
CREATE TABLE ENDERECO(
    IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
    RUA VARCHAR(30) NOT NULL,
    BAIRRO VARCHAR(30) NOT NULL,
    CIDADE VARCHAR(30) NOT NULL,
    ESTADO CHAR(2) NOT NULL,
    ID_CLIENTE INT UNIQUE,
    
    FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE)

);

CREATE TABLE TELEFONE(
    IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
    TIPO ENUM('RES','COM','CEL') NOT NULL,
    NUMERO VARCHAR(10) NOT NULL, 
    ID_CLIENTE INT,

    FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE)

);


/*
    ENDERECO - OBRIGATÓRIO, CADASTRO DE SOMENTE UM.ADD

    TELEFONE -NÃO OBRIGATÓRIO CADASRTRO DE MAIS DE UM (OPCIONAL)

*/


/* CHAVE ESTRANGEIRA É A CHAVE PRIMARIA DE UMA TABELA QUE VAI ATÉ A OUTRA PARA FAZER REFERENCIA ENTRE REGISTROS */

/* 

EM RELACIONAMENTO 1 X 1 A CHAVE ESTRANGEIRA FICA NA TABELA MAIS FRACA 

EM RELACIONAMENTO 1 X N A CHAVE ESTRANGEIRA FICARA SEMRE NA CARNALIDADE N

*/

-- ADICIONANDO OS CLIENTES.
INSERT INTO CLIENTE VALUES(NULL,'JOAO','M','JOAO@IG.COM','78956421574');
INSERT INTO CLIENTE VALUES(NULL, 'CARLOS', 'M', 'CARLOS@IG.COM','123547598521');
INSERT INTO CLIENTE VALUES(NULL, 'ANA', 'F', 'ANA@IG.COM','6874592158743');
INSERT INTO CLIENTE VALUES(NULL, 'CLARA', 'F', NULL,'1475236985472');
INSERT INTO CLIENTE VALUES(NULL, 'JORGE', 'M', 'JORGE@IG.COM','1354786202457');
INSERT INTO CLIENTE VALUES(NULL, 'CELIA', 'F', 'CELIA@IG.COM','9875846215723');

-- ADICIONANDO OS ENDEREÇOS DOS CLIENTES.
INSERT INTO ENDERECO VALUES(NULL, 'RUA ANTOINIO SA','CENTRO','B. HORIZONTE','MG',4);
INSERT INTO ENDERECO VALUES(NULL, 'RUA CAPITÃO ERMES','CENTRO','RIO DE JANEIRO','RJ',1);
INSERT INTO ENDERECO VALUES(NULL, 'RUA PRESIDENTE VARGAS','JARDINS','SÃO PAULO','SP',3);
INSERT INTO ENDERECO VALUES(NULL, 'RUA ALFANDEGA','ESTACIO','RIO DE JANEIRO','RJ',2);
INSERT INTO ENDERECO VALUES(NULL, 'RUA DO OUVIDOR','FLAMENGO','RIO DE JANEIRO','RJ',6);
INSERT INTO ENDERECO VALUES(NULL, 'RUA URUGAIAN','CENTRO','VITORIA','ES',5);
INSERT INTO ENDERECO VALUES(NULL, 'RUA ALFANDEGA','CENTRO','SÃO PAULO','SP',5);

INSERT INTO TELEFONE VALUES(NULL,'CEL','789658423',5);
INSERT INTO TELEFONE VALUES(NULL,'RES','578652187',5);
INSERT INTO TELEFONE VALUES(NULL,'CEL','156578951',1);
INSERT INTO TELEFONE VALUES(NULL,'COM','984253215',2);
INSERT INTO TELEFONE VALUES(NULL,'RES','156876321',1);
INSERT INTO TELEFONE VALUES(NULL,'CEL','132254791',3);
INSERT INTO TELEFONE VALUES(NULL,'COM','257989217',5);
INSERT INTO TELEFONE VALUES(NULL,'RES','321499874',1);
INSERT INTO TELEFONE VALUES(NULL,'CEL','811650156',2);