/* VIEW */

SELECT  C.NOME,
        C.SEXO,
        C.EMAIL,
        T.TIPO,
        T.NUMERO,
        E.BAIRRO,
        E.CIDADE,
        E.ESTADO
FROM CLIENTE C
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE;

/* CRIANDO UMA VIEW */

CREATE VIEW RELATORIO AS 
SELECT  C.NOME,
        C.SEXO,
        C.EMAIL,
        T.TIPO,
        T.NUMERO,
        E.BAIRRO,
        E.CIDADE,
        E.ESTADO
FROM CLIENTE C
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE;


/* UTILIZANDO UMA VIEW */

-- VISUALIZAR UMA VIEW

SHOW TABLES; -- VIUSUALISAR A VIEW NAS TABELAS

-- DELETAR UMA VIEW

DROP VIEW RELATORIO;


-- CRIANDO UMA VIEW DE "FORMA CORRETA"

CREATE VIEW V_RELATORIO AS -- COLOCARA UMA IDENTIFICAÇÃO PARA NÃO SE CONFUNDIR COM UMA TABELA 
SELECT  C.NOME,
        C.SEXO,
        IFNULL(C.EMAIL, 'CLIENTE SEM E-MAIL') AS 'E-MAIL',
        T.TIPO,
        T.NUMERO,
        E.BAIRRO,
        E.CIDADE,
        E.ESTADO
FROM CLIENTE C
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE;


SELECT NOME, NUMERO, ESTADO 
FROM V_RELATORIO;
