/* ORDER BY */

CREATE TABLE ALUNOS(
    NUMERO INT,
    NOME VARCHAR(30)

);

INSERT INTO ALUNOS VALUES(1,'JOAO');
INSERT INTO ALUNOS VALUES(1,'MARIA');
INSERT INTO ALUNOS VALUES(2,'ZOE');
INSERT INTO ALUNOS VALUES(2,'ANDRE');
INSERT INTO ALUNOS VALUES(3,'CLARA');
INSERT INTO ALUNOS VALUES(1,'CLARA');
INSERT INTO ALUNOS VALUES(4,'MAFRA');
INSERT INTO ALUNOS VALUES(5,'JANAINA');
INSERT INTO ALUNOS VALUES(1,'JANAINA');
INSERT INTO ALUNOS VALUES(3,'MARCELO');
INSERT INTO ALUNOS VALUES(4,'GIOVANI');
INSERT INTO ALUNOS VALUES(5,'ANTONIO');
INSERT INTO ALUNOS VALUES(6,'ANA');
INSERT INTO ALUNOS VALUES(6,'VIVIANE'); 


/* FORMAS DE ORGANISAR O ORDER BY */
SELECT * FROM ALUNOS
ORDER BY NUMERO;

SELECT * FROM ALUNOS
ORDER BY 1; -- 1° COLUNA


SELECT * FROM ALUNOS
ORDER BY 2; -- 2° COLUNA


/* ORDENANDO POR MAIS DE UMA COLUNA */

SELECT * FROM ALUNOS
ORDER BY NUMERO, NOME;

-- OU

SELECT * FROM ALUNOS
ORDER BY 1, 2;


/* MESCLANDO ORDER BY COM PROJEÇÃO */

SELECT NOME FROM ALUNOS
ORDER BY NUMERO, NOME;


/* ORDER BY DESC | ASC */

SELECT * FROM ALUNOS
ORDER BY 1 ASC; -- ACENDENTE COMO PADRÃO, NÃO SERÁ PRECISO INFORMALO

SELECT * FROM ALUNOS
ORDER BY 1 DESC; -- DESCENDENTE PRECISA SER INFORMADO

SELECT * FROM ALUNOS
ORDER BY 1, 2 DESC;

SELECT * FROM ALUNOS
ORDER BY 1 DESC, 2 DESC;

/* ORDENANDO COM O JOIN */

SELECT  C.NOME,
        C.SEXO,
        IFNULL(C.EMAIL,'NÃO TEM E-MAIL') AS 'E-MAIL',
        T.TIPO,
        T.NUMERO,
        E.BAIRRO,
        E.CIDADE,
        E.ESTADO
FROM CLIENTE C
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
ORDER BY 1;