/* UPDATE, INSERT E DELETE - DML */

/* ERRO 

INSERT INTO V_RELATORIO VALUES(
    'ANDREIA', 'F', 'ANDREIA@UOL.COM.BR','CEL','88974568749','CENTRO','VITORIA','ES'
);

NÃO É POSSIVEL REALISAR UM DELETE E INSERT POIS ESSA VIEW TEM UM JOIN

*/

UPDATE V_RELATORIO 
SET NOME = 'JOSE'
WHERE NOME = 'JORGE';




CREATE TABLE JOGADORES(
    IDJOGADOR INT,
    NOME VARCHAR(30),
    ESTADO CHAR(2)
);

INSERT INTO JOGADORES VALUES(1,'GUERRERO','RS');
INSERT INTO JOGADORES VALUES(2,'GABIGOL','RJ');
INSERT INTO JOGADORES VALUES(3,'GANSO','RJ');
INSERT INTO JOGADORES VALUES(4,'NENÊ','RJ');
INSERT INTO JOGADORES VALUES(5,'LOVE','SP');


CREATE VIEW V_JOGADORES AS
SELECT NOME, ESTADO
FROM JOGADORES;

SELECT * FROM V_JOGADORES;


DELETE FROM V_JOGADORES
WHERE NOME = 'GUERRERO';

INSERT INTO V_JOGADORES VALUES('GUERRERO','RS');


SELECT * FROM JOGADORES;

SELECT * FROM V_RELATORIO
WHERE SEXO = 'F';