/* RECAP */


CREATE DATABASE GUILHERME;

USE GUILHERME;

CREATE TABLE ALUNOS(
    ALUNO INT,
    NOME VARCHAR(30)
);

SHOW TABLES;

DROP DATABASE COMERCIO;
DROP DATABASE EXEMPLO;
DROP DATABASE PROJETO;
DROP DATABASE TESTE;

/* PROCEDURES */

CREATE DATABASE PROJETO;

USE PROJETO;

CREATE TABLE CURSOS(
    ID_CURSO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL,
    HORAS INT (3) NOT NULL,
    VALOR FLOAT (10,2) NOT NULL

);

INSERT INTO CURSOS VALUES   (NULL,'JAVA',30,500.00),
                            (NULL,'Fundamentos em banco de dados',40,700.00);

/* PROGRAMAÇÃO EM PLSQL E TSPL */

DELIMITER #

STATUS;

CREATE PROCEDURE CAD_CURSO( P_NOME VARCHAR(30), 
                            P_HORAS INT(3), 
                            P_PRECO FLOAT(10,2)
)

BEGIN
    INSERT INTO CURSOS VALUES(NULL,P_NOME,P_HORAS,P_PRECO);

END
#

DELIMITER ;

CALL CAD_CURSO('BI SQL SERVER',35,3000.00);
CALL CAD_CURSO('POWER BI', 20, 1000.00);
CALL CAD_CURSO('TABELAU', 30, 1200.00);

/* CRIAR UMA PROCEDURE PARA CONSULTAR CURSOS */


DELIMITER #

CREATE PROCEDURE BUS_CURSOS(NUMERO INT)
BEGIN

    SELECT  NOME AS 'NOME DO CURSO',
            HORAS AS 'QTD. HORAS',
            VALOR
    
    FROM CURSOS
    WHERE ID_CURSO = NUMERO;

END
#

DELIMITER ;

CALL BUS_CURSOS(4);

/* FUNÇÃO DE AGREGAÇÃO */

CREATE TABLE VENDEDORES(
    IDVENDEDOR INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30),
    SEXO CHAR(1),
    JANEIRO FLOAT(10.2),
    FEVEREIRO FLOAT(10.2),
    MARCO FLOAT(10.2)
);


INSERT INTO VENDEDORES VALUES (NULL,'CARLOS','M',78975.78,78962.57,736819.64)
,(NULL,'MARIA','F',78975.78,78962.57,736819.64)
,(NULL,'ANTONIO','M',78975.78,78962.57,736819.64)
,(NULL,'CLARA','F',78975.78,78962.57,736819.64)
,(NULL,'ANDERSON','M',78975.78,78962.57,736819.64)
,(NULL,'IVONE','F',78975.78,78962.57,736819.64)
,(NULL,'JOAO','M',78975.78,7845242.57,535435.90)
,(NULL,'CELIA','F',258712.98,7239524.77,35154.46)

/* MAX - TRAZ O VALOR MAXIO DE UMA COLUNA */

SELECT MAX(FEVEREIRO) AS MAIOR_FEV
FROM VENDEDORES;

/* MIN - TRAZ O VALOR MINIMO DE UMA COLUNA*/

SELECT MIN(FEVEREIRO) AS MINIMO_FEV
FROM VENDEDORES;

/* AVG - TRAZ O VALOR MEDIO DE UMA COLUNA */

SELECT AVG(FEVEREIRO) AS MEDIA_FEV
FROM VENDEDORES;


/* TRUNCATE DELIMITA O TAMANHO DO VALOR FLOAT 
   TRINCARE(VALOR_FLOAT, CASAS_DECIMAIS)*/

SELECT TRUNCATE(AVG(FEVEREIRO), 2) AS MEDIA_FEV
FROM VENDEDORES;


/* VARIANDO A FUNÇÃO */

SELECT  MIN(FEVEREIRO) AS MINIMO_FEV,
        AVG(FEVEREIRO) AS  MEDIA_FEV,
        MAX(FEVEREIRO) AS MAIOR_FEV