/* SUB QUERY */

/* SUM - TRAZ O VALOR DA COLUNA SOMADA */

SELECT SUM(JANEIRO) AS TOTAL_JAN
FROM VENDEDORES;

SELECT  SUM(JANEIRO) AS TOTAL_JAN,
        SUM(FEVEREIRO) AS TOTAL_FEV,
        SUM(MARCO) AS TOTAL_MAR
FROM VENDEDORES;


/* VENDAS POR SEXO */

SELECT SEXO, TRUNCATE(SUM(MARCO), 2) AS TOTAL_MAR
FROM VENDEDORES
GROUP BY SEXO;


/* VENDEDOR QUE VENDEU MENOS EM MARÇO E SEU NOME */


SELECT MARCO, NOME
FROM VENDEDORES
WHERE MARCO = (SELECT MIN(MARCO) FROM VENDEDORES);

/* VENDEDOR QUE VENDEU MAIS EM FEVEREIRO */

SELECT  FEVEREIRO,
        NOME
FROM VENDEDORES
WHERE FEVEREIRO = (SELECT MAX(FEVEREIRO) FROM VENDEDORES);

/* A MEDIA DOS VENDEDORES */

SELECT  MARCO,
        NOME
FROM VENDEDORES
WHERE MARCO > (SELECT AVG(MARCO) FROM VENDEDORES);