/* RELATORIO GERAL DE TODOS OS CLIENTES */
SELECT C.IDCLIENTE, E.IDENDERECO, T.IDTELEFONE, 
       C.NOME, C.SEXO, C.EMAIL, C.CPF, 
       E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO, 
       T.TIPO, T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE;

/* RElATORIO DE HOMENS */
SELECT C.IDCLIENTE, E.IDENDERECO, IDTELEFONE, 
       C.NOME, C.SEXO, C.EMAIL, C.CPF, 
       E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO, 
       T.TIPO, T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
WHERE SEXO = 'M';


/* ATUALIZANDO OS DADOS */

SELECT * 
FROM CLIENTE
WHERE IDCLIENTE = 11 
OR IDCLIENTE = 12
OR IDCLIENTE = 13
OR IDCLIENTE = 17
OR IDCLIENTE = 18;

SELECT *
FROM CLIENTE 
WHERE IDCLIENTE IN (11,12,13,17,18);


-- ATUALIZANDO OS DADOS
UPDATE CLIENTE
SET SEXO = 'F'
WHERE IDCLIENTE IN (11, 12, 13, 17, 18);

UPDATE CLIENTE
SET SEXO = 'M'
WHERE IDCLIENTE = 15


/* RELATORIO DE MULHERES */
SELECT C.IDCLIENTE, E.IDENDERECO, IDTELEFONE, C.NOME, C.SEXO, C.EMAIL, C.CPF, E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO, T.TIPO, T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
WHERE SEXO = 'F';



/* QUANTIDADE DE HOMENS E MULHES */
SELECT COUNT(*) AS QTD, SEXO 
FROM CLIENTE
GROUP BY SEXO;



/* IDS E EMAIL DAS MULHERES QUE MOREM NO CENTRO DO RIO DE JANEIRO E NÃO TENHAM CELULAR */

SELECT C.NOME, C.EMAIL, 
       E.BAIRRO, E.CIDADE, /* PROJEÇÃO */
       T.NUMERO,T.TIPO
FROM CLIENTE C /*ORIGEMM*/
INNER JOIN ENDERECO E /* JUNÇÃO */
ON C.IDCLIENTE = E.ID_CLIENTE /* JUNÇÃO DE CONDINÇÃO */
INNER JOIN TELEFONE T /* JUNÇÃO */
ON C.IDCLIENTE = T.ID_CLIENTE /* JUNÇÃO DE CONDINÇÃO */
WHERE BAIRRO = 'CENTRO' /* SELEÇÃO */
AND CIDADE = 'RIO DE JANEIRO' 
AND SEXO = 'F' 
AND TIPO != 'CEL'; 

/* PARA UMA CAMPANHA DE PRODUTOS DE BELEZA, O COMERCIAL SOLICITOU UM
RELATÓRIO COM O NOME, EMAIL E TELEFONE CELULAR 
 DAS MULHERES QUE MORAM NO ESTADO DE SÃO PAULO 
VOCÊ TERÁ QUE PASSAR A QUERY PARA GERAR O RELATORIO PARA
O PROGRAMADOR */

SELECT C.NOME, C.EMAIL
       E.ESTADO,
       T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
WHERE ESTADO = 'SP';


SELECT C.NOME, C.EMAIL,
       E.ESTADO,
       T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
WHERE ESTADO = 'SP';
